services:
  postgres:
    image: postgres:16
    container_name: jobtracker_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: jobtracker
      POSTGRES_PASSWORD: jobtracker123
      POSTGRES_DB: jobtracker_db
    ports:
      - "5432:5432"
    volumes:
      - jobtracker_pgdata:/var/lib/postgresql/data

volumes:
  jobtracker_pgdata:
